version: "1"
stack_defaults:
  before_init:
    - ls
    - ls /mnt/workspace
    - ls /mnt/workspace/source
    - /mnt/workspace/source/tbot start --auth-server leaf.tele.ottr.sh:443 --token spacelift-test --destination-dir=/mnt/workspace/tbot-out --data-dir=memory:// --oneshot